name: Ansible Provisioning

on:
  push:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  ANSIBLE_PLAYBOOK_PATH: .environment/ansible-ec2
  ANSIBLE_REMOTE_USER: ec2-user
  PRIVATE_KEY: devops-cyo-key
  ANSIBLE_HOST_KEY_CHECKING: 'False'

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: setup Python virtualenv and install packages
        run: |
          python3 -m venv py3
          source py3/bin/activate
          python -m pip install --upgrade pip
          pip install boto3 botocore ansible==2.10
          echo "ANSIBLE_PYTHON_INTERPRETER=$VIRTUAL_ENV/bin/python3" >> $GITHUB_ENV
          echo "ENVIRONMENT_SETUP=true" >> $GITHUB_ENV
          echo "ANSIBLE_PRIVATE_KEY_FILE=$ANSIBLE_PLAYBOOK_PATH/$PRIVATE_KEY" >> $GITHUB_ENV
      - name: create key pair
        run: |
          ssh-keygen -t rsa -N "" -f $ANSIBLE_PLAYBOOK_PATH/$PRIVATE_KEY
          chmod 400 $ANSIBLE_PLAYBOOK_PATH/$PRIVATE_KEY.pub
      - name: provisioning
        run: |
          source py3/bin/activate
          ansible-playbook $ANSIBLE_PLAYBOOK_PATH/provisioning.yml
      # - name: provide
      #   run: |
      #     source py3/bin/activate
      #     ansible-playbook $ANSIBLE_PLAYBOOK_PATH/setup-nginx.yml --inventory $ANSIBLE_PLAYBOOK_PATH/inventory_aws_ec2.yml
