name: jobs examples

on:
   workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step do job1
        run: echo Hello, world! job1.


  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step do job2
        run: echo Hello, world! Job2.
