name: devops-pipeline

on:
  workflow_dispatch:
    
  #push:
   # branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
      - name: executa comando
        run: echo "Configuração inicial do pipeline"
