name: Pipeline

on:
  push:
    branches: [ main ]

# env:
#   NODE_AUTH_TOKEN: ${{ secrets.JFROG_TOKEN }}
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - uses: actions/setup-node@v2      
      with:
        node-version: '14'
        registry-url: https://valuedriven.jfrog.io/artifactory/default-valuedriven-npm-local/                      
        # always-auth: true
        # cache: 'npm'
    - run: npm --prefix frontend install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.JFROG_TOKEN }}
    - run: npm run --prefix frontend test -- --watchAll=false --coverage=true
    - run: npx --prefix frontend eslint . 
    - run: npm --prefix frontend run build
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: frontend/build


  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   env:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  #     AWS_EC2_METADATA_DISABLED: true
  #   steps:
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: deploy
  #       path: frontend/build
  #   - run: aws s3 cp frontend/build s3://devops-cyo --recursive --acl public-read      
